### ISSUE TITLE
Support Subquery Exists

### ISSUE THREAD

**Issue by cj848** [line/kotlin-jdsl#123]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/5905201/197430447-86614808-caf1-4f44-9a31-12f4b2ffb687.png">
Currently kotlin-jdsl does not support the CriteriaBuilder.exists method. An implementation of this method is required.

A function like below code should be implemented in jdsl.

think about what kind of appearance is suitable for jdsl.

-- korean
현재 kotlin-jdsl 은 CriteriaBuilder.exists 메소드를 지원하지 않습니다. 이 메소드의 구현이 필요합니다.

아래 코드와 같은 기능이 jdsl에 구현 되어야 합니다.

어떤 모습이 jdsl 에 적합한지 같이 고민해보았으면 합니다.

@shouwn @huisam @pickmoment 

```kotlin
CriteriaBuilder builder = entityManager.getCriteriaBuilder();
 
CriteriaQuery<Post> query = builder.createQuery(Post.class);
Root<Post> p = query.from(Post.class);
 
ParameterExpression<Integer> minScore = builder.parameter(Integer.class);
Subquery<Integer> subQuery = query.subquery(Integer.class);
Root<PostComment> pc = subQuery.from(PostComment.class);
subQuery
    .select(builder.literal(1))
    .where(
        builder.equal(pc.get(PostComment_.POST), p),
        builder.gt(pc.get(PostComment_.SCORE), minScore)
    );
 
query.where(builder.exists(subQuery));
 
List<Post> posts = entityManager.createQuery(query)
    .setParameter(minScore, 10)
    .getResultList();
```

generated SQL
```sql
SELECT
    p.id AS id1_0_,
    p.title AS title2_0_
FROM post p
WHERE EXISTS (
    SELECT 1
    FROM post_comment pc
    WHERE
        pc.post_id=p.id AND
        pc.score > ?
)
ORDER BY p.id
```

**Comment by shouwn** [comment]
@cj848 죄송합니다. 이번주에 업무가 너무 많아서 확인이 힘들 것 같습니다. 다음주 월요일에 확인 가능할 것 같은데 괜찮을까요?

**Comment by cj848** [comment]
@shouwn 괜찮습니다.
제 생각에는
where(exists(subquery))  형태가 되면 좋지않을까 싶은데 의견 부탁드려요~

**Comment by shouwn** [comment]
@cj848 `where(exists(subquery))`형태가 딱 좋을 것 같습니다. 👍 

--- english
`where(exists(subquery))` is the best form.

**Comment by huisam** [comment]
-- korean
결국 select query 를 기반으로 하는 것이기 때문에 저도 다른 의견은 없습니다.

-- english
In the end, I have no other opinion because it is based on select query.

**Comment by kihwankim** [comment]
Hello, I am interesting in this issue
So I made this function and this is result

![image](https://user-images.githubusercontent.com/19687080/199696214-73f6d284-f19d-4257-8e09-d36c486bf134.png)

Can I add the test code and send PR?

@cj848 @shouwn @huisam @pickmoment

**Comment by cj848** [comment]
Wow. That's great. If you check that not exists works well, you can post a PR.

**Comment by kihwankim** [comment]
@cj848 
Okay! Thank you for giving me the opportunity to develop the function of this wonderful project.

I will try that one!

**Comment by cj848** [comment]
@kihwankim 
You can post your PR at any time. I was going to work on it, but it was difficult because I didn't have time, but thank you for participating.

**Comment by shouwn** [comment]
@kihwankim @cj848 2.0.7.RELEASE is released
