### ISSUE TITLE
Equivalent of nested JOIN FETCH and LEFT JOIN FETCH

### ISSUE THREAD

**Issue by martinformi** [line/kotlin-jdsl#142]
I am trying now to rewrite hibernate HQL to JDSL but I am not sure I know to convert `JOIN FETCH` and `LEFT JOIN FETCH` when they refer one to another

```
select DISTINCT i from myentity i JOIN FETCH i.translations t LEFT JOIN FETCH t.tags 
```

How we could achieve this?

**Comment by cj848** [comment]
Let's name your entity classes MyEntity, Translation, and Tag and show an example.
```kotlin
selectDistinct(entity(MyEntity::class))
from(MyEntity::class)
fetch(MyEntity::translations)
fetch(Translations::tags, JoinType.LEFT)
```
It is expected that you will write the code as above.

If it is resolved, please close it :)
