### ISSUE TITLE
Connection leak when coroutine canceled

### ISSUE THREAD

**Issue by namjug-kim** [line/kotlin-jdsl#159]
kotlin-jdsl converts Uni to Coroutine through 'Mutiny#awaitSuspended'.
Look more closely here, the `awaitSuspend` function implemented by suspendCancellableCoroutine and invoke UniSubscriber#cancel when coroutine canceled.

However, hiberante-reactive `MutinySessionFactoryImpl` does not provide close process for cancel.

``` java
private<S extends Mutiny.Closeable, T> Uni<T> withSession(
          Uni<S> sessionUni,
          Function<S, Uni<T>> work,
          Context.Key<S> contextKey) {
        return sessionUni.chain( session -> Uni.createFrom().voidItem()
              .invoke( () -> context.put( contextKey, session ) )
              .chain( () -> work.apply( session ) )
              .eventually( () -> context.remove( contextKey ) )
              .eventually(session::close)
        );
}
```

below code not be executed when Uni(withSession) is canceled and Session not closed forever.
```
.eventually( () -> context.remove( contextKey ) )
.eventually(session::close)
```

Im not sure this hibernate-reactive session behavior is intended :(
related issue in [hibernate-reactive issue](https://github.com/hibernate/hibernate-reactive/issues/1436)

To use current version(1.1.9.Final) hibernate-reactive session, Uni must be converted to coroutine using suspendCoroutine instead of suspendCancellableCoroutine.

``` kotlin
suspend fun <T> Uni<T>.awaitSingle() = suspendCoroutine<T> { continuation ->
    subscribe().with(
        { item -> continuation.resume(item) },
        { failure -> continuation.resumeWithException(failure) }
    )
}
```

**Comment by namjug-kim** [comment]
i'll create pr for fix this issue. https://github.com/namjug-kim/kotlin-jdsl/commit/7cc1ec85809abb68c92efe0ab24c7243d76bb859

**Comment by namjug-kim** [comment]
This issue will be fixed in Hibernate-reactive 😀

With current version avoid using **waitSuspending** to prevent cancellation if call **withSession** outside of the vertx context.

**Comment by cj848** [comment]
I checked the issue link. thanks. Even if mutiny is fixed, it seems to be solved. Since jdsl reactive doesn't enforce hibernate reactive/mutiny version, it seems that the problem can go away if the version goes up. We will not take action right away, and please comment when the version is up.

**Comment by cj848** [comment]
With the change to jdsl 3.0, the wrapper that creates the session and the wrapper responsible for execution are also no longer provided. For more details, please refer to the https://kotlin-jdsl.gitbook.io/docs/ document and issue #446.
