### ISSUE TITLE
pageQuery + join 쿼리 사용법 문의

### ISSUE THREAD

**Issue by sinkyoungdeok** [line/kotlin-jdsl#176]
안녕하세요. Kotlin, Webflux, Mysql 환경에서 jdsl을 사용하고 있습니다.
singleQueryOrNull, singleQuery, listQuery에서는 fetch 혹은 join 쿼리 정상 동작하는 것을 확인했는데요. 
pageQuery 에서는 fetch 혹은 join 쿼리가 없는 것 같더라구요. 
(fetch는 import가 안되고, join을 사용하면 `could not initialize proxy - no Session` 오류가 발생합니다)
참고로 fetchType은 EAGER로 설정해두었습니다.
혹시 지원 예정인걸까요? 아니면 제가 잘못 사용한 걸까요?

제가 사용했던 쿼리는 다음과 같습니다. 

### 성공 쿼리
```kotlin
override suspend fun findById(competitionId: Long): Competition? {
        return queryFactory.singleQueryOrNull {
            select(entity(Competition::class))
            from(entity(Competition::class))
            fetch(Competition::prizes)
            where(col(Competition::id).equal(competitionId))
        }
    }
```

### 실패 쿼리 (import 안됨)
```kotlin
override suspend fun findAll(pageable: Pageable): Slice<Competition> {
        return queryFactory.pageQuery(pageable) {
            select(entity(Competition::class))
            from(entity(Competition::class))
            fetch(Competition::prizes)
        }
    }
```

감사합니다.

**Comment by cj848** [comment]
https://junhyunny.github.io/spring-boot/jpa/jpa-fetch-join-paging-problem/
이 글을 참고해주시기 바랍니다.
fetch join 을 페이징에서 제공할 경우 메모리 조인의 문제가 발생할 수 있습니다.
페이징 자체가 아예 불가능한것은 아니고, 
https://github.com/line/kotlin-jdsl/issues/130#issuecomment-1308192712

이 글에 있는 @shouwn 님의 글을 참고해주시기 바랍니다

**Comment by sinkyoungdeok** [comment]
@cj848 덕분에 해결했습니다 감사합니다!
