### ISSUE TITLE
Collection Fetch Join Set 타입 사용법 문의 

### ISSUE THREAD

**Issue by sinkyoungdeok** [line/kotlin-jdsl#179]
안녕하세요.   
jpa에서는 둘이상의 컬렉션타입을 fetch join할 때, set타입으로 해결하곤 했는데요.   
jdsl에서는 set타입으로 선언해서 조회할 시 에러가 뜨더라구요.  

set 타입으로 사용 할 수 있는 방법이 있을까요? 

### 성공 Collection
```kotlin
@OneToMany(mappedBy = "competition", cascade = [CascadeType.PERSIST])
val prizes: MutableList<Prize> = mutableListOf(),
```

### 실패 Collection
```kotlin
@OneToMany(mappedBy = "competition", cascade = [CascadeType.PERSIST])
val prizes: MutableSet<Prize> = mutableSetOf(),

**Comment by cj848** [comment]
What error occurs?
-- korean
어떤 에러가 발생하나요?

**Comment by sinkyoungdeok** [comment]
```
org.hibernate.SessionException: collections cannot be fetched by a stateless session
```

The above error occurs.

**Comment by cj848** [comment]
재현 가능한 최소한의 프로젝트를 github 샘플로 제출해주시면 확인해보겠습니다.

**Comment by sinkyoungdeok** [comment]
이렇게 구성해서 드려도 될지 모르겠지만 우선 공유 드립니다. 

https://github.com/FONE1light/fone-backend-jdsl/pull/111

서버 시작전에 
```
cd docker
docker-compose up -d 
```
로 db, redis 띄우고 서버 실행하면 정상 구동 됩니다.

그리고나서 PR에 test.http파일을 준비해두었는데, intellij로 이 파일을 열어서 순서대로 테스트해볼 수 있도록 구성해놓았습니다.

감사합니다!

**Comment by cj848** [comment]
현재 업무량이 많아서 확인을 못하고 있는 상황입니다. 시간이 되는데로 체크해보겠습니다.

**Comment by sinkyoungdeok** [comment]
@cj848 넵 시간되실 때 확인 부탁드립니다!

**Comment by cj848** [comment]
확인이 되신듯 하여 close 하겠습니다.
제가 정신이 없어 계속 보질 못했네요. 불편을 드려 죄송합니다 :)
