### ISSUE TITLE
No Autowireing

### ISSUE THREAD

**Issue by rafal-szyszka** [line/kotlin-jdsl#189]
I've imported your dependency to my project:

```        
        <dependency>
            <groupId>com.linecorp.kotlin-jdsl</groupId>
            <artifactId>spring-data-kotlin-jdsl-starter</artifactId>
            <version>${spring-data-kotlin-jdsl-starter.version}</version>
        </dependency>
```

and tried to use it as you described:
```java
@Service("prodactivvity.Project")
@Transactional
class ProjectPersistenceRepo(
    private val repo: ProjectRepository,
    private val metadataExtractor: MetadataExtractor,
    private val queryFactory: SpringDataQueryFactory,
) {}
```

but i get this error:
`required a bean of type 'com.linecorp.kotlinjdsl.spring.data.SpringDataQueryFactory' that could not be found.`

**Comment by cj848** [comment]
If you submit it as a minimal reproducible code sample github project, I'll check it out. Currently there is no problem within my project.

**Comment by cj848** [comment]
I will close the issue as there are no further comments.
