### ISSUE TITLE
InValueSpec Incorrectly providing Conjunction for empty Collections

### ISSUE THREAD

**Issue by MrThreepwood** [line/kotlin-jdsl#191]
We found a mistake in our code today where we were querying our table for records with specific IDs. Specifically something similar to `select * from table where id in (ids)`. We found that this query was taking a very long time to complete and realized we were actually calling this when we had an empty list of IDs.

Looking through the code, the class com.linecorp.kotlinjdsl.query.spec.predicate.InValueSpec has a line that terrifies me: `if (rights.isEmpty()) return criteriaBuilder.conjunction()` 

Shouldn't this be a disjunction? Heck, I'd much prefer an exception. If I'm understanding this correctly the code:
```kotlin
deleteQuery<TEntity> {
      where(col(property).in(values))
}.executeUpdate()
```

Would result in the sql `Delete from table where 1 = 1`. Am I understanding this correctly?

**Comment by cj848** [comment]
This is a trade off between convenience and risk. There is no correct answer, so it is currently implemented that way.

**Comment by MrThreepwood** [comment]
I'm not following? In what case does an empty list being a conjunction rather than a disjunction make sense? And even if there is, wouldn't it be better to just throw? Is there a way to change this functionality by overriding something?

This is a potential source for data breaches and huge loss of data. I don't see how this could be anything other than a critical security vulnerability.

**Comment by cj848** [comment]
I think I took this issue too lightly.
I think your opinion is valid, and I will review your PR and release it as soon as it is merged. Thank you so much for your contribution.
