### ISSUE TITLE
support for ilike

### ISSUE THREAD

**Issue by jkromski** [line/kotlin-jdsl#202]
From what I see there is no support for `ilike` expression.

Can we add this please in similar way as `like` is done:

```java
queryFactory.listQuery<Entity> {
    select(entity(Book::class))
    from(entity(Book::class))
    where(column(Book::title).ilike("%DrAgOn%"))
}
```

**Comment by cj848** [comment]
https://github.com/line/kotlin-jdsl/issues/61
Replaced by this link answer. Support is currently difficult.
