### ISSUE TITLE
Join with a custom condition

### ISSUE THREAD

**Issue by nikita715** [line/kotlin-jdsl#205]
Does kotlin-jdsl support custom conditions in joins? I need to make a left join with `on` condition like this in criteria api:
```
val userQuizResult = quiz.join<QuizEntity, UserQuizResultEntity>("userQuizResults", JoinType.LEFT)
userQuizResult.on(criteriaBuilder.equal(userQuizResult.get<Long>("profileId"), 100))
```
and it has to look like this in sql:
```
left join user_quiz_result on quiz.id = user_quiz_result.quiz_id and user_quiz_result.profile_id = 100
```

**Comment by loalexzzzz** [comment]
> I also want to make it possible to `left join` when there is an `on` condition. This will be applied to Kotlin-JDSL 3.0.
> 
> 
> 
> Because the Criteria API does not allow `left join` when there is an `on` condition...

May I know when the 3.0 version will release?

**Comment by shouwn** [comment]
Kotlin JDSL 3.0 is scheduled for October.

**Comment by shouwn** [comment]
Hi @nikita715 @loalexzzzz .

Kotlin JDSL 3.0.0-SNAPSHOT has been released in snapshot repository. With 3.0.0, on condition is now possible. If you are still using Kotlin JDSL, please test it.

We apologize for the long wait and thank you for your patience.

If the snapshot version doesn't allow you to write the code you need, please reopen this issue.

**Comment by shouwn** [comment]
I think the following docs will help you get started with Kotlin JDSL 3.0.0.
https://kotlin-jdsl.gitbook.io/docs/
