### ISSUE TITLE
select exist query

### ISSUE THREAD

**Issue by maxzycon** [line/kotlin-jdsl#237]
hi, can i do like this 

```
select 
    id,
    exists(select 1 from image_tree t1 where t1.parent_id = t.id) has_child_rows
from image_tree t
```

**Comment by cj848** [comment]
@maxzycon 
you can use subquery check this document https://github.com/line/kotlin-jdsl#subquery

**Comment by maxzycon** [comment]
i have tried before, thanks @cj848  for answering my question 
`select 
    id,
    exists(select 1 from image_tree t1 where t1.parent_id = t.id) has_child_rows
from image_tree t`

not 
`select 
    id
from image_tree t where  exists(select 1 from image_tree t1 where t1.parent_id = t.id) has_child_rows`

whether the query can be done, if so how to selectMulti has_child_rows to custom DTO?

**Comment by shouwn** [comment]
Hi @maxzycon Sorry for the late reply...

As you replied, Kotlin-JDSL does not support exist queries in select clause. The reason is that the Criteria API does not support it. 

It's very late, but Kotlin-JDSL is currently designing the structure of Kotlin JDSL 3.0. I'm planning to complete it by October this year, so I think I can apply in October.

I'm sorry that Kotlin-JDSL cannot provide the function you want.

**Comment by shouwn** [comment]
I'm considering the structure as shown in the picture below for what I'm currently planning.

It is largely divided into three "DSL", "Query", and "Engine" parts, "DSL" is presentation layer, "Query" is a DTO layer, and Engine is an execution layer.

![image](https://user-images.githubusercontent.com/31586979/236157097-761aa15e-daba-4c44-817b-8807ede09ee2.png)

**Comment by shouwn** [comment]
Hi @maxzycon 

Kotlin JDSL 3.0.0-SNAPSHOT has been released in snapshot repository. With 3.0.0, predicates in a select clause is now possible. If you are still using Kotlin JDSL, please test it.

We apologize for the long wait and thank you for your patience.

If the snapshot version doesn't allow you to write the code you need, please reopen this issue.

The following docs will help you get started with Kotlin JDSL 3.0.0.
https://kotlin-jdsl.gitbook.io/docs/
