### ISSUE TITLE
How to write the left join sql with on a.id = b.id

### ISSUE THREAD

**Issue by loalexzzzz** [line/kotlin-jdsl#251]
Hi all, how to write the following sql in kotlin-jdsl?

SELECT *
FROM facebook
JOIN linkedin
ON facebook.name = linkedin.name
WHERE facebook.name = Matt OR linkedin.city = "SF"

It would be greatly appreciated if anyone could provide an example.

**Comment by loalexzzzz** [comment]
Are there any alternatives way to archive it, if there are no way implement LEFT JOIN ON?

like below

https://stackoverflow.com/questions/7510481/how-can-i-substitute-a-left-join-in-sql

**Comment by shouwn** [comment]
You can use join like the code below.

```kotlin
select(entity(Facebook::class))
from(entity(Facebook::class))
join(Linkedin::class, on { col(Facebook::name).equal(col(Linkedin::name)) })
whereOr(
    col(Facebook::name).equal("Matt"),
    col(Linkedin::city).equal("SF"),
)
```

The join-on method has the same effect as inner join because it changes join to cross join and adds the on condition to the where clause.

```sql
select facebook0_.id   as id1_6_,
       facebook0_.name as name2_6_
from facebook facebook0_
join linkedin linkedin1_
where facebook0_.name = linkedin1_.name
  and (facebook0_.name = 'Matt' or linkedin1_.city = 'SF')
```

**Comment by shouwn** [comment]
I wanted to make a Left join on method like you said, but with my knowledge it was impossible. 😭

**Comment by shouwn** [comment]
This issue is being discussed in #205, so I am closing this issue and moving the conversation to #205 for further discussion. This issue will be resolved in Kotlin JDSL 3.0.0 and a SNAPSHOT version has been released. 

Also thank you loalexzzzz for your patience!

**Comment by shouwn** [comment]
@loalexzzzz Sure!

In Kotlin JDSL 3.0.0, `join()` has an `on()` method. For example, there are two unrelated entities: `Author` and `BookAuthor`

```kotlin
@Entity
@Table(name = "author")
class Author(
    @Id
    @Column(name = "author_id")
    val authorId: Long,

    @Column(name = "name")
    var name: String,
)

@Entity
@Table(name = "book_author")
class BookAuthor(
    @Id
    @Column(name = "author_id")
    val authorId: Long,
)
```

To find `Author` who hasn't written a book in this relationship, you can use `leftJoin()` and `on()`:

```kotlin
interface AuthorRepository : JpaRepository<Author, Long>, KotlinJdslJpqlExecutor

val authors = authorRepository.findAll {
    select(
        entity(Author::class),
    ).from(
        entity(Author::class),
        // This is left join for unrelated entities: Author and BookAuthor
        leftJoin(BookAuthor::class).on(path(Author::authorId).equal(path(BookAuthor::authorId))),
    ).where(
        path(BookAuthor::authorId).isNull(),
    ).orderBy(
        path(Author::authorId).asc(),
    )
}

authors.forEach {
    println(it)
}
```

And since Kotlin JDSL 2.X and Kotlin JDSL 3.0.0 can be used together in a single application, you can test only new code with Kotlin JDSL 3.0.0.

**Comment by shouwn** [comment]
You can test Kotlin JDSL 3.0.0 right now by adding the following snapshot repository to your build settings.

```
repositories {
    maven(url = "https://oss.sonatype.org/content/repositories/snapshots")
}
```

https://kotlin-jdsl.gitbook.io/docs/jpql-with-kotlin-jdsl#snapshot
