### ISSUE TITLE
OrderBy in pageQuery

### ISSUE THREAD

**Issue by VictorAlbertos** [line/kotlin-jdsl#262]
Is there a reason why `pageQuery` does not expose the `OrderByDsl` as `listQuery` does? How can I sort the rows then if there is no orderBy in `pageQuery`?

And the same limitation applies to `groupBy`, as far as I can see.

**Comment by cj848** [comment]
please refer to this [comment](https://github.com/line/kotlin-jdsl/issues/176#issuecomment-1404862616)
