### ISSUE TITLE
Support JPA 3.0 Specification

### ISSUE THREAD

**Issue by cj848** [line/kotlin-jdsl#27]
JPA 3.0 is a specification created to avoid patent disputes with Java, and compared to 2.2, there is no difference except for package and name.

Comparing the case of Hibernate, it is supported as a separate library like hibernate-core-jakarta.

It seems that kotlin-jdsl and kotlin-jdsl-core-jakarta should come out in pairs.

Currently, JPA 3.0 specification supports only two vendors, Eclipselink and Hibernate.

-- korean
JPA 3.0 은 Java 와의 특허 분쟁을 피하기 위해 만들어진 스펙으로 실제 2.2와 비교해보면 package 나 명칭 제외하고는 다르지 않습니다.

하이버네이트의 사례를 비교해 보면 hibernate-core-jakarta 와 같이 별도의 라이브러리로 지원하고 있습니다.

kotlin-jdsl 도 kotlin-jdsl-core-jakarta 와 같은 형태의 쌍들이 나와야 할 것으로 보입니다.

현재 JPA 3.0 스펙은 Eclipselink, Hibernate 두개의 vendor 만 지원하고 있습니다.

**Comment by cj848** [comment]
@shouwn spring 6.0이 나왔습니다. 업그레이드 하는 순간 jdsl 을 사용할 수 없습니다.
query dsl 개선 전에 JPA 3.0 지원을 하는게 어떨까요?

루틴한 복사 붙여넣기 작업일 가능성이 크지만 그래도 하는게 계속 사용하기 위한 중간 과정이라도 될 수 있을것 같습니다.

**Comment by shouwn** [comment]
@cj848 JDSL 3.0 doesn't have development resources at this time, so I think we will keep 2.0 for a while. So it may be meaningful to support Jakarta in 2.0.

Tankonyko has previously created a Jakarta support code in https://github.com/line/kotlin-jdsl/issues/73. Could you talk with Tankonyko and proceed with this content?

Currently, My development schedule is full until April next year, so I don't think I can lead this.

-- korean
JDSL 3.0 개발 리소스가 없기 때문에 2.0 버전이 한동안 유지될 것 같습니다. 그래서 2.0 버전에서 Jakarta 지원이 의미 있을 것으로 보입니다.

Tankonyko 님이 https://github.com/line/kotlin-jdsl/issues/73 PR을 통해 Jakarta 지원 코드를 작성해주신 적이 있습니다. Tankonyko 님과 이야기 하여 이 부분 진행이 가능할까요?

제가 내년 4월까지 개발 일정이 가득 차 있어서 이 부분 리드가 불가능할 것 같습니다.
