### ISSUE TITLE
Prepared Statements

### ISSUE THREAD

**Issue by iainroyle** [line/kotlin-jdsl#315]
Hello,
Does your API support prepared statements, ie. queries with named or positional parameters (or as per JPA, CriteriaBuilder.parameter)?
Thanks.

**Comment by shouwn** [comment]
Hi, iainroyle.

We don't have plan to support prepared statements, but we would support named or positional parameters.

Named or positional parameters will be included in the Kotlin-JDSL 3.0. In the case of JPA in 3.X, the values included in all queries will be changed to the named parameter

We are in the process of developing version 3.X, so we don't plan to support this in version 2.X.


We are thinking about which interface will be good for the user. If you tell me the reason why you want the named or positional parameter and the signature you want, I will reflect it on 3.X.

To show you what is currently under development, all the values are parameterized in the rendered String as below.
> The reason why the sample is positional parameter is because JPQL is still under development, so I can only show you the Native SQL sample.

```kotlin
@Test
fun insert2() {
    // given
    val insert: InsertQuery<NonNullTable> = sql(Normal) {
        insertInto(
            table(NonNullTable::class),
        ).columns(
            column(NonNullTable::column1),
            column(NonNullTable::column2),
        ).values(
            byte1,
            short1,
        ).values(
            parameter(byte2),
            parameter(short2),
        ).values(
            listOf(
                parameter(byte3),
                parameter(short3),
            ),
        ).values(
            byte4,
            short4,
        )
    }

    // when
    val actual = render(insert)

    // then
    val expected = SqlRendered(
        query = "INSERT INTO non_null_table(column1, column2) VALUES (?, ?), (?, ?), (?, ?), (?, ?)",
        parameters = indexedParams {
            param(byte1)
            param(short1)
            param(byte2)
            param(short2)
            param(byte3)
            param(short3)
            param(byte4)
            param(short4)
        },
    )

    assertThat(actual).isEqualTo(expected)
}
```

```kotlin
fun <T : Any> EntityManager.createQuery(
    query: JpqlQuery<*>,
    context: RenderContext,
    resultClass: KClass<T>,
): TypedQuery<T> {
    val rendered = jpqlRenderer.render(query, context)

    val renderedQuery = rendered.query
    val renderedParams = rendered.parameters

    return createQuery(renderedQuery, resultClass.java).apply {
        setParameters(renderedParams)
    }
}
```

**Comment by iainroyle** [comment]
Hi,

Thanks for your reply.

The main reason I would like parameterisable queries is for execution performance. Without parameters, the DB will usually have to compile the query each time, which is inefficient, of course.

I happened to be looking at a read query, so I would imagine something like the following to parameterise the query...

```
fun getUser(em: EntityManager, firstName: String, lastName: String): User =
    QueryFactoryImpl(CriteriaQueryCreatorImpl(em), SubqueryCreatorImpl()).
    singleQuery<User> {
        val param1 = Param<String>()
        val param2 = Param<String>()
        where(
            and(
                column(Driver::firstName).equal(param1),
                column(Driver::lastName).equal(param2)))
        setParam(param1, firstName)
        setParam(param2, lastName)
    }
```

Which should create a query such as:

`select * from User where firstName = ? and lastName = ?`

Does something like that work?

Thanks

**Comment by shouwn** [comment]
Kotlin-JDSL 3.0 supports a form similar to what you expect.

```kotlin
val firstName = "John"
val lastName = "David"

select(
    entity(User::class),
).from(
    entity(User::class),
).whereAnd(
    field(User::firstName).equal(param(firstName)),
    field(User::lastName).equal(param(lastName)),
)
```

```sql
SELECT User.* FROM User User WHERE User.firstName = ? AND User.lastName = ?
```

```
```

The `param` method means to extract the value that has been passed on to the parameter by bind value of query.


I am thinking about constants as you said.

**Comment by shouwn** [comment]
And I have one more thing to ask.

Do you want to use positional parameter and named parameter selectively when using binding value in JPQL?

Because I don't think I need to use positional parameter in JPQL so I wonder if I should implement it.

**Comment by iainroyle** [comment]
Ok, firstly, I think that what you have so far in 3.0 is pretty good. I would be happy with that implementation as it stands, as it solves the main problem of having to continuously compile the queries.

To answer your last question, I think that named parameters are all that are needed. I don't think positional parameters are necessary.

Literals (or 'inline') would be a good addition. I would not worry about SQL injection. I do not think that it should be the concern of this library to protect against such a thing. It should be the concern of whatever code is using the library to scan any inputs for SQL injection attacks before using those literals. If Kotlin-JDSL was scanning for injection attacks, you would likely end up scanning everything twice anyway.

Another slight optimisation... If you were to use the parameter style I suggested:

```
        val param1 = Param<String>()
        val param2 = Param<String>()
        where(
            and(
                column(Driver::firstName).equal(param1),
                column(Driver::lastName).equal(param2)))
        setParam(param1, firstName)
        setParam(param2, lastName)
```

..then there are some minor optimisations that can be performed, eg. using the same parameter in different positions...

```
        val param1 = Param<String>()
        where(
            and(
                column(Driver::firstName).equal(param1),
                column(Driver::lastName).equal(param1)))
        setParam(param1, firstName)
```

This is a minor optimisation, but I think it is strictly more correct, and is how it's done in Criteria Queries.

However, as I said, what you have so far in 3.0 is good and will be fine in most situations.

I appreciate your efforts, btw. It's a nice library.

**Comment by shouwn** [comment]
Accepting your suggestion, I thought of the following code.

```kotlin
val selectQuery = jpql {
    select(
        entity(User::class),
    ).from(
        entity(User::class),
    ).whereAnd(
        field(User::firstName).equal(param(name = "param1")),
        field(User::lastName).equal(param(name = "param1")),
        field(User::age).greaterThan(value(20))
    )
}

val userInput: Map<String, Any?> =  mapOf("param1" to "John")


val (query, params) = renderer.render(selectQuery, userInput, context)

// query == "SELECT User.* FROM User User WHERE User.firstName = :param1 AND User.lastName = :param1 AND User.age = :1"
// params == mapOf("param1" to "John", "1" to 20)
```

This code can be included in 3.0.0, so I will develop this custom parameter in 3.0.0.

Thank you so much for your suggestion!

**Comment by iainroyle** [comment]
No problem, happy to help.
The code looks good so I'll look forward to version 3.0.0!
Thanks again.

**Comment by shouwn** [comment]
Hi @iainroyle 

Kotlin JDSL 3.0.0-SNAPSHOT has been released in snapshot repository!

If the snapshot version doesn't allow you to write the code you need, please reopen this issue!

The following docs will help you get started with Kotlin JDSL 3.0.0.
https://kotlin-jdsl.gitbook.io/docs/

**Comment by iainroyle** [comment]
Great news. I will try it out soon.
Many thanks.
