### ISSUE TITLE
Implement JpqlSerializer for JpqlCoalesce

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#333]
### Backgrounds
- In Kotlin JDSL 3.0.0, the Query objects no longer know how to draw themselves as SQL String.
- The Query object is drawn in JPQL String by `JpqlSerializer`.

### Requirements
- Please implement  JpqlSerializer that draws `JpqlCoalesce` as a SQL String.
- Please implement a unit test for the implemented class.

### Contribution
- Please check if there is an assignee in this issue. And if it don't have an assignee, please change the assignee to yourself.
- Please check the commit convention through the commitlint.config.js file. The commit  convention also described in the PR template.
- When you use intellij, please set the code style through the .editorconfig file.
- Please create the PR for develop/3.0.0 as the base branch.
- If you have any questions, please leave comment in Kotlin-JDSL Discord Channel in [LINE Open Source](https://discord.gg/7FH8c6npmg)

**Comment by sbcoba** [comment]
제가 가져 갈게요 ~

**Comment by cj848** [comment]
@sbcoba 이슈 할당 받으신지 좀 오래되었는데 구현이 안되어서요.. 제가 가져가도 괜찮을까요?

**Comment by sbcoba** [comment]
아 죄송합니다. 부탁드리겠습니다.
