### ISSUE TITLE
Implement JpqlSerializer for JpqlMin

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#343]

**Comment by shouwn** [comment]
I modified the assignee to @jbl428 through [this comment](https://github.com/line/kotlin-jdsl/issues/342#issuecomment-1666744633).

**Comment by jbl428** [comment]
Please assign this issue to me.

**Comment by shouwn** [comment]
This issue is closed by https://github.com/line/kotlin-jdsl/pull/396
