### ISSUE TITLE
Implement JpqlSerializer for JpqlNullIf

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#347]
### Backgrounds
- In Kotlin JDSL 3.0.0, the Query objects no longer know how to draw themselves as SQL String.
- The Query object is drawn in JPQL String by `JpqlSerializer`.

### Requirements
- Please implement  JpqlSerializer that draws `JpqlNullIf` as a SQL String.
- Please implement a unit test for the implemented class.

### Contribution
- Please check if there is an assignee in this issue. And if it don't have an assignee, please change the assignee to yourself.
- Please check the commit convention through the commitlint.config.js file. The commit  convention also described in the PR template.
- When you use intellij, please set the code style through the .editorconfig file.
- Please create the PR for develop/3.0.0 as the base branch.
- If you have any questions, please leave comment in Kotlin-JDSL Discord Channel in [LINE Open Source](https://discord.gg/7FH8c6npmg)

**Comment by waveofmymind** [comment]
안녕하세요!
assign 부탁드립니다 :)

**Comment by shouwn** [comment]
Hi @waveofmymind 

I haven't checked my mail properly yesterday and today. The email history shows that you requested to assign [the ticket](https://github.com/line/kotlin-jdsl/issues/349), but I don't see them in the current thread. Did you remove your comments because I didn't respond? 

If so, this is my fault. If you'd like to contribute, please comment again.

**Comment by waveofmymind** [comment]
@shouwn 
Yes. I requested to be assigned the ticket for JpqlPlus, but since I'm still not familiar with contributing, I intend to first tackle the JpqlNullIf that I've already been assigned.
Once this issue is resolved, I will leave a comment again in the future!
Thank you for your attention.

**Comment by shouwn** [comment]
Oh, I see. Thank you for your contribution!

**Comment by shouwn** [comment]
This issue is closed by #405
