### ISSUE TITLE
Implement JpqlSerializer for JpqlSome

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#350]
### Backgrounds
- In Kotlin JDSL 3.0.0, the Query objects no longer know how to draw themselves as SQL String.
- The Query object is drawn in JPQL String by `JpqlSerializer`.

### Requirements
- Please implement  JpqlSerializer that draws `JpqlSome` as a SQL String.
- Please implement a unit test for the implemented class.

### Contribution
- Please check if there is an assignee in this issue. And if it don't have an assignee, please change the assignee to yourself.
- Please check the commit convention through the commitlint.config.js file. The commit  convention also described in the PR template.
- When you use intellij, please set the code style through the .editorconfig file.
- Please create the PR for develop/3.0.0 as the base branch.
- If you have any questions, please leave comment in Kotlin-JDSL Discord Channel in [LINE Open Source](https://discord.gg/7FH8c6npmg)

**Comment by shouwn** [comment]
Hi @jbl428 I have modified the JpqlSerialiser test to reduce repetition and make it a more safer test. 

Please check it out and if you have any questions, leave a comment in this issue or on Discord

**Comment by jbl428** [comment]
@shouwn 
I looked at the code, and it seems very useful. :)
If you don't mind, may I create some test files for the JpqlSerializers you've implemented?

**Comment by shouwn** [comment]
@jbl428 Sure!

It would be very helpful if you could make the test code.

If you make the test code and find something I've implemented incorrectly, please feel free to fix it, and if you find anything weird, feel free to leave a comment!

**Comment by shouwn** [comment]
This issue is closed by #402
