### ISSUE TITLE
Implement JpqlSerializer for JpqlLike

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#375]
### Backgrounds
- In Kotlin JDSL 3.0.0, the Query objects no longer know how to draw themselves as SQL String.
- The Query object is drawn in JPQL String by `JpqlSerializer`.

### Requirements
- Please implement  JpqlSerializer that draws `JpqlLike` as a SQL String.
- Please implement a unit test for the implemented class.

### Contribution
- Please check if there is an assignee in this issue. And if it don't have an assignee, please change the assignee to yourself.
- Please check the commit convention through the commitlint.config.js file. The commit  convention also described in the PR template.
- When you use intellij, please set the code style through the .editorconfig file.
- Please create the PR for develop/3.0.0 as the base branch.
- If you have any questions, please leave comment in Kotlin-JDSL Discord Channel in [LINE Open Source](https://discord.gg/7FH8c6npmg)

**Comment by jbl428** [comment]
@shouwn 
I have some question during implementing test for this.
According to JPQL docs, Like expression has the following syntax.

```
string_expression [NOT] LIKE pattern_value [ESCAPE escape_character]
```

However, `JpqlLike` does not have property for escape character.

```kt
@Internal
data class JpqlLike internal constructor(
    val value: Expression<String>,
    val pattern: Expression<String>,
) : Predicate
```

I'm curious whether this is something that's missing or if you have plans to add it.
And if you need to add it, I'm wondering whether it would be better to use `stringLiteral` from `Expressions` or to add a new character literals.

```kt
    @SinceJdsl("3.0.0")
    fun charactreLiteral(string: Char): Expression<String> {
        return JpqlLiteral.CharLiteral(string)
    }
```

**Comment by shouwn** [comment]
@jbl428 
Since I have no experience with ESCAPE, I didn't implement it because I didn't know how to actually add it. 

Like you said, I looked it up and it seems that ESCAPE only allows one `character`, so it seems like a good idea to create a `charLiteral()` method.

If you don't mind, could you implement this? You don't need to implement tests of the DSL and QueryModel because I will implement these.

**Comment by shouwn** [comment]
It's okay if you don't implement it! I'd be happy if you just implemented `JpqlLikeSerializer`.
