### ISSUE TITLE
Support spring batch

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#413]
### Requirements
- Please implement a spring-batch-support module to help execute the JPQL query using `JpaItemReader`s.
- You should implement the `JpaQueryProvider` for Kotlin JDSL
- You should implement a unit test and an integration test, and the integration test is implemented through the example module.

**Comment by jyunkim** [comment]
Please assign this issue to me.

**Comment by cj848** [comment]
It appears that spring-batch support has been completed, so we will close the issue.
