### ISSUE TITLE
In the develop branch environment, renovate settings must be set only under the example.

### ISSUE THREAD

**Issue by cj848** [line/kotlin-jdsl#458]
### Requirements
Currently, kotlin-jdsl applies renovate settings to all dependencies.
This causes continuous dependency merge to occur in the main branch and automatically detects changes to the main branch, making continuous deployment impossible.

Therefore, renovate should be applied only on the develop branch.

Additionally, kotlin-jdsl must operate from the minimum version it can support, so branches other than example will not arbitrarily update the library version.

However, since it is necessary to check through continuous integration whether there are any problems in operating up to the latest existing version, it is necessary to create a PR that can automatically update only the dependencies used under the example folder.

-- korean
현재 kotlin-jdsl 은 모든 dependency 에 대해 renovate 설정을 적용하고 있습니다.
이는 main 브랜치에 지속적인 dependency merge 가 일어나게 되고 main 브랜치에 대한 변경을 자동 감지하여 지속적인 배포를 불가능하게 합니다.

그러므로 develop 브랜치에서만 renovate 가 적용 되어야 합니다.

또한 kotlin-jdsl 은 지원할 수 있는 최소 버전부터 동작해야 하므로 example 이 아닌 다른 브랜치는 임의로 라이브러리 버전 업데이트를 진행하지 않습니다.

다만 현존하는 최신버전까지 동작하는데 문제 없는지 지속적인 통합을 통해서 확인이 필요하기 때문에 example 폴더 아래에 사용되는 dependency 에 한해서는 자동으로 업데이트를 할 수 있는 PR 을 만들도록 해야 합니다.

**Comment by jbl428** [comment]
@cj848 
Have you already started working on this? If it's okay, I'd like to take care of it.

My idea was to copy the file `example.libs.versions.toml` and then configure `renovate.json` to only read that file. 
I've already handled this task in my forked repository. 
If you think this approach is suitable, I'll create a pull request. :)

**Comment by cj848** [comment]
@jbl428 sure. great. If you are working on this issue, you must fork the develop branch so that the merge target branch is also develop. I will assign an issue to you.

**Comment by shouwn** [comment]
It seems like renovate only checks the example dependency. Thank you @jbl428 so much for your help!

https://github.com/line/kotlin-jdsl/pull/463
