### ISSUE TITLE
postgresql 지원되나요?

### ISSUE THREAD

**Issue by ahnjunwoo-rsquare** [line/kotlin-jdsl#516]
postgresql 지원되나요?

**Comment by shouwn** [comment]
Postgresql 지원을 문의 주신 것은 2가지 의미를 가지고 있다고 생각합니다.

1. Kotlin JDSL의 JPQL이 Postgresql을 지원하는지 여부
2. Kotlin JDSL이 가지는 향후 Native Query 지원 계획에 Postgresql이 포함 되어 있는지 여부

첫 번째의 경우 JPA를 통해 Postgresql을 사용할 수 있는 것으로 알고 있기 때문에 가능합니다.

두 번째의 경우는 고민중에 있습니다. Oracle을 지원할 생각을 가지고 있었지만 Postgresql을 사용하시는 분들이 많아 보여 Oracle 대신에 Postgresql 지원을 먼저 할까 생각하고 있습니다.
