### ISSUE TITLE
@DataJpaTest 에서 KotlinJdslJpqlExecutor findSlice error

### ISSUE THREAD

**Issue by KYHK** [line/kotlin-jdsl#526]
2.2 버전 잘쓰고 있다가 v3 릴리즈 되서 소스 바꿔보고 있는데
@DataJpaTest 테스트 환경에서
KotlinJdslJpqlExecutor  No property 'findSlice' found for type 엔티티 에러가 나옵니다.
혹시 어떻게 해결해야하는지 알려주실수 있나요?

해당 에러 발생은 KotlinJdslJpqlExecutorImpl 의존성 주입하여 KotlinJdslJpqlExecutor 자체 사용할땐 문제가 없었으며
jpa repository, KotlinJdslJpqlExecutor 선언된 인터페이스 들에서 문제가 발생했습니다.

**Comment by shouwn** [comment]
이것은 조금 다른 이야기이지만 저희 팀에서는 여러 DB를 붙이면서 Custom 설정 코드가 많아져 아래처럼 별도의 Slice 테스트 어노테이션을 작성해서 개발하고 있습니다.

`@ImportAutoConfiguration`을 계속 붙이시는 것에 주저함이 드신다면 아래 처럼 우리 팀만의 Slice 테스트 어노테이션을 작성해보시는 방법도 좋을 것으로 보입니다.

```kotlin
@Target(AnnotationTarget.ANNOTATION_CLASS, AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
@MustBeDocumented
@Inherited
@BootstrapWith(JpaTestContextBootstrapper::class)
@ExtendWith(SpringExtension::class)
@OverrideAutoConfiguration(enabled = false)
@TypeExcludeFilters(JpaTypeExcludeFilter::class)
@Transactional
@AutoConfigureCache
@AutoConfigureCrypto
@AutoConfigureJpa
@AutoConfigureJackson
@AutoConfigureTestEntityManager
@ImportAutoConfiguration
annotation class JpaTest(
    val properties: Array<String> = [],

    @get: PropertyMapping("spring.jpa.show-sql")
    val showSql: Boolean = true,

    @get: PropertyMapping("spring.data.jpa.repositories.bootstrap-mode")
    val bootstrapMode: BootstrapMode = BootstrapMode.DEFAULT,

    val useDefaultFilters: Boolean = true,

    val includeFilters: Array<ComponentScan.Filter> = [],

    val excludeFilters: Array<ComponentScan.Filter> = [],

    @get: AliasFor(annotation = ImportAutoConfiguration::class, attribute = "exclude")
    val excludeAutoConfiguration: Array<KClass<*>> = []
)

class JpaTestContextBootstrapper : SpringBootTestContextBootstrapper() {
    override fun getProperties(testClass: Class<*>): Array<String> =
        MergedAnnotations.from(testClass, MergedAnnotations.SearchStrategy.INHERITED_ANNOTATIONS)
            .get(JpaTest::class.java)
            .getValue("properties", Array<String>::class.java).orElse(null)
}

class JpaTypeExcludeFilter(
    testClass: Class<*>,
) : StandardAnnotationCustomizableTypeExcludeFilter<JpaTest>(testClass)

```

**Comment by KYHK** [comment]
@Retention(AnnotationRetention.RUNTIME)
@Import(LineKotlinQueryDslConfig::class)
@ImportAutoConfiguration(classes = [KotlinJdslAutoConfiguration::class])
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ExtendWith(SpringExtension::class)
internal annotation class RepositoryTest



@Configuration
class LineKotlinQueryDslConfig(
    val em: EntityManager,
) {
    @Bean
    fun springDataQueryFactory(): SpringDataQueryFactory {
        return SpringDataQueryFactoryImpl(
            criteriaQueryCreator = CriteriaQueryCreatorImpl(em),
            subqueryCreator = SubqueryCreatorImpl(),
        )
    }

    @Bean
    fun jdsl(): KotlinJdslJpqlExecutor {
        return KotlinJdslJpqlExecutorImpl(
            entityManager = em,
            renderContext = JpqlRenderContext()
        )
    }
}

감사합니다 auto configuration 선언하니 잘 되네요

**Comment by shouwn** [comment]
아~ 이미 다른 Configuration도 등록해서 사용하고 계셨군요. 해결 되어서 다행이네요.

이 부분은 다른 분들도 헷갈릴 것 같아 Docs에 추가해놓겠습니다. 🎉

**Comment by KYHK** [comment]
잘 사용하고 있습니다 항상 감사합니다!
