### ISSUE TITLE
I hope kotlin-jdsl support kotlin 1.8.x

### ISSUE THREAD

**Issue by grandwhale** [line/kotlin-jdsl#560]
I am currently using kotlin-jdsl v2.2.1 and I would like to update it to v3. However, there are several reasons why I cannot update it from Kotlin 1.8.x. 

I assume that there are some technical reasons for choosing Kotlin 1.9 for kotlin-jdsl v3, but Kotlin 1.8 was released only about a year ago, and some companies find it difficult to upgrade Kotlin versions. I would like you to understand this point.

**Comment by shouwn** [comment]
There is no technical reason for Kotlin JDSL to use Kotlin 1.9. I just used the latest version of Kotlin to test if Kotlin JDSL works with the K2 compiler. 

I think we can lower the minimum required version of Kotlin. It would be nice if Kotlin had something like the jvm toolchain. I'll have to check it.

**Comment by shouwn** [comment]
cc. @cj848

**Comment by cj848** [comment]
@shouwn I completely agree with you. We believe that setting the version to the minimum requirements, excluding the example directory, will be helpful for user convenience.

**Comment by shouwn** [comment]
Hi grandwhale.

I will deploy the fix next Tuesday to make it available over 1.7.

**Comment by shouwn** [comment]
Hi @grandwhale 

I deployed 3.3.0. The Kotlin API version of 3.3.0 is targeted for 1.7, so it should work with 1.8. I'm going to close this issue, but please reopen this issue if something doesn't work.

**Comment by grandwhale** [comment]
@shouwn I did not expect kotlin 1.8 support to be possible at all, but it is such good news. I am very grateful for your help.
