### ISSUE TITLE
Support Arithmetic function ABS

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#574]
### Backgrounds
- Kotlin JDSL does not yet support an arithmetic function `ABS`.

### Objects
- Support an arithmetic function ABS.

### Requirements
- Creates `abs()` function in `com.linecorp.kotlinjdsl.dsl.jpql.Jpql` for supporting an arithmetic function ABS.

### Contribution
- Please check if there is an assignee in this issue. And if it don't have an assignee, please leave comment to assign.
- Please check the commit convention through the commitlint.config.js file. The commit  convention also described in the PR template.
- When you use intellij, please set the code style through the .editorconfig file.
- Please create the PR for develop as the base branch.
- If you have any questions, please leave comment in Kotlin-JDSL Discord Channel in [LINE Open Source](https://discord.gg/7FH8c6npmg)

**Comment by jbl428** [comment]
I would like to work on this issue.

**Comment by shouwn** [comment]
Hi jbl428! 🥇 

I assigned this issue to you. Thanks for your help!
