### ISSUE TITLE
Support Arithmetic function FLOOR

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#577]
### Backgrounds
- Kotlin JDSL does not yet support an arithmetic function `FLOOR`.

### Objects
- Support an arithmetic function FLOOR.

### Requirements
- Creates `floor()` function in `com.linecorp.kotlinjdsl.dsl.jpql.Jpql` for supporting an arithmetic function FLOOR.

### Contribution
- Please check if there is an assignee in this issue. And if it don't have an assignee, please leave comment to assign.
- Please check the commit convention through the commitlint.config.js file. The commit  convention also described in the PR template.
- When you use intellij, please set the code style through the .editorconfig file.
- Please create the PR for develop as the base branch.
- If you have any questions, please leave comment in Kotlin-JDSL Discord Channel in [LINE Open Source](https://discord.gg/7FH8c6npmg)

**Comment by sinkyoungdeok** [comment]
Can I contribute to this issue?

**Comment by shouwn** [comment]
Hi sinkyoungdeok! Of course! 

I changed the assignee to you! Thank you for your help!
