### ISSUE TITLE
Support Arithmetic function MOD

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#581]
### Backgrounds
- Kotlin JDSL does not yet support an arithmetic function `MOD`.

### Objects
- Support an arithmetic function MOD.

### Requirements
- Creates `mod()` function in `com.linecorp.kotlinjdsl.dsl.jpql.Jpql` for supporting an arithmetic function MOD.

### Contribution
- Please check if there is an assignee in this issue. And if it don't have an assignee, please leave comment to assign.
- Please check the commit convention through the commitlint.config.js file. The commit  convention also described in the PR template.
- When you use intellij, please set the code style through the .editorconfig file.
- Please create the PR for develop as the base branch.
- If you have any questions, please leave comment in Kotlin-JDSL Discord Channel in [LINE Open Source](https://discord.gg/7FH8c6npmg)

**Comment by Dogacel** [comment]
I would like to contribute to this issue, would be glad if you can assign, thanks!

**Comment by shouwn** [comment]
Hi Dogacel!

I assigned this issue to you. Thank you for your help!

**Comment by shouwn** [comment]
It's been 3 weeks since the last comment. I'm going to close the PR created by Dogacel and change the assignee of this issue.

**Comment by graceful-martin** [comment]
Hello, I would like to be assigned to the specific issue.

**Comment by shouwn** [comment]
I assigned this issue to graceful-martin. Thanks for your help!
