### ISSUE TITLE
Include join examples

### ISSUE THREAD

**Issue by nort3x** [line/kotlin-jdsl#60]
first of all this project is brilliant!
examples are all single entity oriented and not specifically helping with joins,
join has many overloads, i'm interested in left-join for instance and now i'm not sure which signature to use

**Comment by shouwn** [comment]
Hi, nort3x. I'm sorry for the late reply. I think you asked us about what to do with the left join, is that right? Or do you mean to add some examples for joins?

**Comment by nort3x** [comment]
hi @shouwn ,
joins are probably in top tree pitfalls of any orm-related tool, 
so i'm just asking for rich documentation.
suppose a new users want to test kotlin-jdsl for the first time,
they probably try to replace one of their query with it to test it out and the chance of it being a trivial query is very low, so examples should have a broader perspective and cover a little more complex situations

**Comment by shouwn** [comment]
Oh, I see. Thank you for your suggestion.

I will think about examples of using join and make a document.

**Comment by pemassi** [comment]
Is there any update for this? I have tried to use `LEFT JOIN`, but I gave up because there is a lack of explanation.

I feel this project needs more documentation to make many users use this library.

**Comment by cj848** [comment]
The document was created by the PR above. Can you close the issue if you decide that the desired part has been met?
