### ISSUE TITLE
Support Datetime function CURRENT_TIME

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#600]
### Backgrounds
- Kotlin JDSL does not yet support a datetime function `CURRENT_TIME`.

### Objects
- Support a datetime function `CURRENT_TIME`.

### Requirements
- Creates `currentTime()` function in `com.linecorp.kotlinjdsl.dsl.jpql.Jpql` for supporting a datetime function `CURRENT_TIME`.

### Contribution
- Please check if there is an assignee in this issue. And if it don't have an assignee, please leave comment to assign.
- Please check the commit convention through the commitlint.config.js file. The commit  convention also described in the PR template.
- When you use intellij, please set the code style through the .editorconfig file.
- Please create the PR for develop as the base branch.
- If you have any questions, please leave comment in Kotlin-JDSL Discord Channel in [LINE Open Source](https://discord.gg/7FH8c6npmg)

**Comment by meengi07** [comment]
I'm working on the issue.

**Comment by shouwn** [comment]
I apologize for the late check. I have assigned this issue to you. Thanks for your help!
