### ISSUE TITLE
Support Datetime function LOCAL TIME

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#603]
### Backgrounds
- Kotlin JDSL does not yet support a datetime function `LOCAL TIME`.

### Objects
- Support a datetime function `LOCAL TIME`.

### Requirements
- Creates `localTime`() function in `com.linecorp.kotlinjdsl.dsl.jpql.Jpql` for supporting a datetime function `LOCAL TIME`.

### Contribution
- Please check if there is an assignee in this issue. And if it don't have an assignee, please leave comment to assign.
- Please check the commit convention through the commitlint.config.js file. The commit  convention also described in the PR template.
- When you use intellij, please set the code style through the .editorconfig file.
- Please create the PR for develop as the base branch.
- If you have any questions, please leave comment in Kotlin-JDSL Discord Channel in [LINE Open Source](https://discord.gg/7FH8c6npmg)

**Comment by TheAndreiUrsu** [comment]
Hello, could I be assigned to this issue? I would like to contribute.

**Comment by shouwn** [comment]
Hi TheAndreiUrsu!

Yes, I changed the assignee to you! Thank you for your help!
