### ISSUE TITLE
@Id, @EmbeddedId에 대해 궁금한 점이 있습니다.

### ISSUE THREAD

**Issue by devbelly** [line/kotlin-jdsl#607]
안녕하세요. jpa를 공부하면서 jdsl를 익히기 위해 example 폴더를 보다가 궁금한 점이 있어 질문드립니다.

```
@Entity
@Table(name = "book")
class Book(
    @Id
    @EmbeddedId
    @AttributeOverride(name = "value", column = Column(name = "isbn"))
    val isbn: Isbn,

    @Column(name = "title")
    var title: String,

    @Column(name = "image_url")
    var imageUrl: String,
```

@EmbeddId를 사용하는 Book 클래스에서 추가적으로 @Id 어노테이션을 사용하신 이유가 있는지 궁금합니다.

<img width="701" alt="image" src="https://github.com/line/kotlin-jdsl/assets/67682840/09d486f9-830f-40f8-a1ea-3ca05890e83e">

JPA 2.2 명세서에 따라 @Id 어노테이션이 추가적으로 필요하지 않은 것 같아서 질문드립니다.

**Comment by shouwn** [comment]
안녕하세요! 이 부분은 제가 인지하지 못 했습니다. 

Id에 해당하는 필드에 제가 습관적으로 Id 어노테이션을 붙였는데, 이는 잘못된 사용법이었군요. example에서 Id 어노테이션을 제외하도록 하겠습니다. 

저의 잘못을 확인해주셔서 감사합니다.

**Comment by shouwn** [comment]
Id 어노테이션을 제거하고 테스트가 정상 동작하는 것을 확인한 뒤에 머지하였습니다.

혹시 제가 잘못 사용한 다른 어노테이션이 있으면 이 이슈를 다시 오픈해서 언제든지 말씀주세요!

이 이슈는 close 하겠습니다. JDSL에 관심을 주셔서 감사합니다.

**Comment by devbelly** [comment]
혹시 이 내용으로는 컨트리뷰션이 되기 어렵나요?🥹
