### ISSUE TITLE
KotlinJdslJpqlExecutor findAll 이 `List<T?>` 를 반환하는 이유가 있나요?

### ISSUE THREAD

**Issue by ShindongLee** [line/kotlin-jdsl#608]
`List<T>` 로 사용하고 싶은데, `List<T?>` 를 반환하는 이유가 궁금합니다.

기존 2버전대의 SpringDataQueryFactory.listQuery는 `List<T>` 를 반환했었는데요, 3.3.1 로 버전을 올리니 `List<T?>` 를 반환해서 filterNotNull을 해야하는데 의도된 것인지 궁금합니다!

**Comment by shouwn** [comment]
안녕하세요! 
이유는 JPQL로 쿼리를 어떻게 작성하냐에 따라 반환 된 리스트의 항목 중 null이 포함될 수 있기 때문입니다.

DTO Projection의 경우에는 모든 ROW에 생성자를 호출하기 때문에 nullable한 조회 결과가 나오지 않지만, column이나 entity를 조회하는 경우 null 값이 포함될 수 있습니다. 가장 간단한 예로는 nullable한 column을 조회하는 경우입니다.

처음에는 nullable 여부를 타입추론으로 알아내 List<T>의 nullable을 핸들링하려고 했지만, join으로 인해 완벽한 nullable 추론을 할 수 없다는 것을 개발하면서 알게 되었습니다. 그래서 3.0에서는 타입에 대한 nullable 추론을 제거하면서 반환 타입을 무조건 nullable로 고정하게 되었습니다. 

getSlice나 getPage 등 non-null한 리스트를 반환하는 메소드를 만들 수 있지만, 이 경우 사용자마다 이러한 메소드를 바라보는 관점이 달라 만들지 않게 되었습니다. 예를 들면 JpaRepository에서 `get`은 reference를 가져오는 키워드로 쓰였던 적이 있습니다.

이렇게 
- nullable한 값이 반환될 수 있다는 점. 
- 이는 join으로 인해 타입추론으로 해결이 불가능하다는 점. 
- 추가적인 메소드는 사용자 관점에 따라 해석의 범위가 너무 다른 점. 
들의 이유로 nullable을 반환하게 되었습니다.

이 부분은 FAQ로 문서에 별도로 남겨놓을 예정입니다.

**Comment by ShindongLee** [comment]
@shouwn 안녕하세요! 빠르고 친절한 답변 감사합니다.
