### ISSUE TITLE
Proposal: Adding ROW_NUMBER Function

### ISSUE THREAD

**Issue by graceful-martin** [line/kotlin-jdsl#662]
Hibernate supports ROW_NUMBER() function like this [https://vladmihalcea.com/hibernate-jpql-window-functions/](Ref)
but in kotlin-jdsl, there has no feature like ROW_NUMBER()
I propose to make this feature

**Comment by shouwn** [comment]
It's easy for the Kotlin JDSL to support Hibernate's ROW_NUMBER() function. However, since this function is not in the JPA specification and is not a feature most users will need, I'd like you to implement your own custom DSL.

**Comment by shouwn** [comment]
I will close this issue. If there's anything else you'd like to talk about, please reopen the issue.
