### ISSUE TITLE
Documentation of how Kotlin JDSL is different from jOOQ and QueryDSL

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#666]
### Backgrounds
- Someone might wonder how Kotlin JDSL differs from jOOQ or QueryDSL. 

### Objects
- Documenting FAQ of how Kotlin JDSL is different from jOOQ and QueryDSL.

### Requirements
- The FAQ should be written with a focus on the metamodel.

**Comment by progress0407** [comment]
Hi there, nice to see you back.
I apologize for the bottleneck in the last PR, but we were very busy... T.T
I think I can explain the benefits of Line-JDSL in this section.
If you don't mind, may I suggest something that I've documented about this?

**Comment by cj848** [comment]
@progress0407 sure. sorry for delay this issue, i assigned to you

**Comment by progress0407** [comment]
> @progress0407 sure. sorry for delay this issue, i assigned to you

Thanks for giving me the work!
