### ISSUE TITLE
Documentation of why Kotlin JDSL returns a nullable list in the Spring Support module.

### ISSUE THREAD

**Issue by shouwn** [line/kotlin-jdsl#667]
### Backgrounds
- Someone might wonder why Kotlin JDSL returns a nullable list in the Spring Support module.

### Objects
- Documenting FAQ of why Kotlin JDSL returns a nullable list in the Spring Support module.

### References
- [Answer in Korean](https://discord.com/channels/1087271586832318494/1124136741650042931/1196059310392873060)

**Comment by progress0407** [comment]
Well, I'd like to document this as well... It seems like a rather difficult topic to me. 🤣

**Comment by shouwn** [comment]
Hi @progress0407 Thanks for your contribution!

@cj848 Is it okay if you assign this task to progress0407? 
If you don't mind, please change the assignee to progress0407.
