### ISSUE TITLE
Could I edit small parts of the document?

### ISSUE THREAD

**Issue by progress0407** [line/kotlin-jdsl#672]
## Backgrounds
As I was going through the documentation, I saw some things that I thought could be fixed.

## Objects
Make the following modifications.

### Adding kotlin language identifier

> how-can-i-see-the-generated-query.md

<img width="435" alt="image" src="https://github.com/line/kotlin-jdsl/assets/66164361/e489290e-6943-4ba9-80f0-6585849d6b5c">

### Erasing comment

> custom-dsl.md

<img width="435" alt="image" src="https://github.com/line/kotlin-jdsl/assets/66164361/de37a45a-c7a8-4008-8c3a-e97f089a34db">

(I apologize if this was an intentional comment.)

## Requirements
Edit the document.

**Comment by shouwn** [comment]
I forgot to declare the code block as kotlin, please add it if you don't mind.

However, the comment in the second document is intended, so please keep it.

**Comment by progress0407** [comment]
> I forgot to declare the code block as kotlin, please add it if you don't mind.
> 
> However, the comment in the second document is intended, so please keep it.

Ok, I got it !...
