### ISSUE TITLE
Inquire how to use CRUD method metadata

### ISSUE THREAD

**Issue by veluxer62** [line/kotlin-jdsl#677]
안녕하세요.

Spring Data JPA에서 지원하는 `@Lock` 관련해서 몇가지 문의사항이 있어 글을 남깁니다.

### 배경설명

저희팀에서 기존에 사용하던 QueryDSL을 JDSL로 전환하기 위해서 아래와 같은 방식으로 JDSL을 적용해서 사용하고 있습니다.

```kotlin
class CustomAdminRepositoryImpl(
    private val kotlinJdslJpqlExecutor: KotlinJdslJpqlExecutor,
) : CustomAdminRepository {
    override fun findRole(filter: RoleFilter): Optional<Role> {
        return kotlinJdslJpqlExecutor
            .findAll {
                val idPredicate = filter.id?.let { path(Role::getId).eq(it) }
                val namePredicate = filter.name?.let { path(Role::name).eq(it) }

                select(entity(Role::class))
                    .from(entity(Role::class))
                    .where(
                        and(
                            idPredicate,
                            namePredicate,
                        ),
                    )
            }
            .firstOrNull()
            .let { Optional.ofNullable(it) }
    }
}
```

### 문의사항

- 만약 `findRole`함수에 비관적 잠금을 설정할 수 있는 방법이 있을까요?
- https://github.com/line/kotlin-jdsl/pull/665 에서 보면 잠금에 대한 metadata 지원이 병합된걸로 보이는데 언제쯤 릴리즈될까요?

감사합니다.

**Comment by shouwn** [comment]
veluxer62 님 안녕하세요. 

비관적 락 설정을 원하신다면 EntityManager를 직접 참고하시는 걸 추천드립니다. 

com.linecorp.kotlinjdsl.support.spring.data.jpa.extension 패키지를 확인해보시면 Kotlin JDSL의 Query를 실행할 수 있는 EntityManager의 extension function이 정의된 것을 보실 수 있습니다.

이를 이용해 작성해주신 쿼리를 변경하면 다음과 같이 작성하실 수 있습니다.

Spring을 사용하실 경우 JpqlRenderContext 객체가 Bean으로 자동 등록되어 있기 때문에 바로 사용하실 수 있습니다.

```kotlin
val query = jpql {
    val inPredicate = filter.id?.let { path(Role::getId).eq(it) }
    val namePredicate = filter.name?.let { path(Role::name).eq(it) }
    
    select(
        entity(Role::class),
    ).from(
        entity(Role::class),
    ).whereAnd(
        inPredicate,
        namePredicate
    )
}

return entityManager.createQuery(query, jpqlRenderContext).apply { 
    lockMode = LockModeType.PESSIMISTIC_WRITE
}.resultList.firstOrNull().let { Optional.ofNullable(it) }
```

metadata 지원의 경우는 추천드리지 않습니다. metadata 지원을 개발한 이유는 Spring이 요구하는 인터페이스를 지키기 위해서 개발한 것으로 일반적인 유스케이스로서 제공하고자 만든 것은 아닙니다.

**Comment by veluxer62** [comment]
@shouwn
상세히 설명해주셔서 감사합니다!
제안해주신 방법으로 적용 검토해보겠습니다 :)
감사합니다.
