### ISSUE TITLE
조회 조건으로 받은 값이 null 이거나 빈 문자열("")일 때 where 절을 생략하고 싶습니다. 방법이 있을까요?

### ISSUE THREAD

**Issue by noohss** [line/kotlin-jdsl#743]

**Comment by ririnto** [comment]
https://kotlin-jdsl.gitbook.io/docs/v/ko-1/jpql-with-kotlin-jdsl/predicates

링크에 따르면, 

```
만약 and() 와 or()로 넘어온 Predicate가 모두 null 이거나 비어 있으면, and()의 경우에는 1 = 1로 or()의 경우에는 0 = 1로 해석됩니다. 그렇기 떄문에 다이나믹 쿼리를 만들 때 조심해야 합니다.
```

라고 설명되어 있습니다.

따라서, `.takeUnless(String::isNullOrEmpty)`를 고려하시지요.

**Comment by shouwn** [comment]
ririnto 님의 답변으로 해소될 것으로 보이기 때문에 이 이슈는 클로즈하겠습니다.

추가 문의사항이 있으시면 이슈를 다시 오픈해주세요.
