### ISSUE TITLE
[Question] join() 함수를 이용해서 Left Join을 시도 중인데 컴파일 오류가 자꾸발생하는데 레퍼런스들과 달라서 문의드립니다.

### ISSUE THREAD

**Issue by mykim8710** [line/kotlin-jdsl#744]
먼저 이렇게 좋은 JDSL을 개발해 주셔서 감사합니다.

kotlin + springboot, jpa 환경에서 Kotlin JDSL을 도입하여 개발중에 있습니다.

** 사용버전 및 dependency
kotlin version : 2.0.0
springboot version : 3.3.1

implementation("com.linecorp.kotlin-jdsl:spring-data-kotlin-jdsl-starter-jakarta:2.2.1.RELEASE")   // kotlin-jdsl

연관관계를 맺지 않았지만 id값으로 두 엔티티에 대해 Left Join을 시도하려고 하는데 자꾸만 컴파일 오류가 발생해서 문의드립니다.

아래는 현상입니다.

`override fun findAllPageByAdmin(pageable: Pageable, request: FindAllFaqRequest): Page<FaqResponseByAdminInList> {

        return queryFactory.pageQuery(
            FaqResponseByAdminInList::class.java,
            pageable
        ) {
            select(
                listOf(
                    column(Faq::id),
                    column(Faq::title),
                    column(Faq::content),
                    column(Faq::category),
                    column(Faq::createdAt),
                    column(Faq::isPublished),
                    column(Faq::isFrequency),
                    column(AdminMember::name),
                    column(AdminMember::memberId),
                )
            )
            from(Faq::class)
            join(AdminMember::class, column(Faq::createdId).equal(column(AdminMember::id))) // inner join은 작동함
            
            // left join 컴파일 오류
            join(AdminMember::class, JoinType.LEFT) {
                on(column(Faq::createdId)).equal(column(AdminMember::id))
            }
            whereAnd(
                column(Faq::active).isTrue(),
                request.keyword?.let { column(Faq::title).like("%$it%") },
            )
        }
    }`
![스크린샷 2024-07-31 오후 3 18 04](https://github.com/user-attachments/assets/ecc2aa01-1ba7-46e5-961a-33362648217d)

**Comment by cj848** [comment]
boot 3 버전의 경우 jdsl 3 이상의 버전을 사용하셔야 합니다.

**Comment by mykim8710** [comment]
implementation("com.linecorp.kotlin-jdsl:spring-data-kotlin-jdsl-starter-jakarta:2.2.1.RELEASE")  이게 최신 버전으로 나오는데 혹시 말씀해주신 jdsl 3 이상의 버전은 어디서 확인할수 있을지 말씀부탁드리빈다.

**Comment by mykim8710** [comment]
> boot 3 버전의 경우 가급적 jdsl 3 이상의 버전을 사용하시는것을 권장 합니다. 최신버전을 사용하실경우 사용법이 2.x 버전이랑 많이 다릅니다. 큰 틀의 방법은 비슷하나 웹에 공개된 문서를 참고하셔서 작업하시는게 좋을 것 같습니다.

implementation("com.linecorp.kotlin-jdsl:spring-data-kotlin-jdsl-starter-jakarta:2.2.1.RELEASE") 이게 최신 버전으로 나오는데 혹시 말씀해주신 jdsl 3 이상의 버전은 어디서 확인할수 있을지 말씀부탁드립니다.

**Comment by shouwn** [comment]
@mykim8710 안녕하세요.

Kotlin JDSL 3.X부터 maven artifacts 및 패키지가 변경되었습니다.
https://kotlin-jdsl.gitbook.io/docs/jpql-with-kotlin-jdsl#add-kotlin-jdsl-dependencies
![image](https://github.com/user-attachments/assets/beeed0b5-2673-4a6c-92d3-5186c2aa44d2)

위 가이드를 따라 설치하실 수 있습니다.

Kotlin JDSL 2.X와 Kotlin JDSL 3.X는 둘 다 완전히 다른 패키지 구조를 가지고 있기 때문에 함께 사용이 가능합니다.
그렇기 때문에 신규 코드는 Kotlin JDSL 3.X로 작성하고 과거 코드는 점진적으로 Kotlin JDSL 2.X에서 Kotlin JDSL 3.X 버전으로 변경하는 방식을 추천드립니다.

**Comment by shouwn** [comment]
Kotlin JDSL 3.X의 사용법은 [example](https://github.com/line/kotlin-jdsl/blob/main/example/spring-data-jpa/src/test/kotlin/com/linecorp/kotlinjdsl/example/spring/data/jpa/jpql/select/SelectExample.kt) 및 [공식 문서](https://kotlin-jdsl.gitbook.io/docs)를 준비해놓았기 때문에 이를 통해서 사용방법을 확인하실 수 있습니다.
