### ISSUE TITLE
사용법 문의

### ISSUE THREAD

**Issue by LeeMH** [line/kotlin-jdsl#76]
안녕하세요. 
이번 자그마한 프로젝트에 queryDSL 대신 jdsl 넣어서 개발중입니다.
좋은 라이브러리 만들어 주셔서 감사합니다.
사용중 궁금한 점이 있어 문의 드립니다.

사용환경

* kotlin-jdsl : 2.0.4
 
* hibernate: 5.4.32

* boot: 2.5.7

1. 단건 select 방법

- select count(id) from member 이런식으로 단건으로 리턴되는 쿼리 입니다.
- 현재는 selectMulti를 사용해서 List로 fetch하고 첫번째 값만 리턴하고 있습니다.

2. @Embedded 타입에 대한 column 사용법

- 현재 날짜관련된 필드를 아래와 같이 사용하고 있습니다.

```
@Embeddable
class UpdatedAt(
    @Column(name = "updated_at")
    val ts: Long,

    @Column(name = "updated_date")
    val date: String,

    @Column(name = "updated_time")
    val time: String
) {
    companion object {
        fun create(ts: Long): UpdatedAt {
            return UpdatedAt(ts, toDateStr(ts), toTimeStr(ts))
        }
    }
}
```

- 실제 쿼리에서는 UpdatedAt의 ts 필드만을 이용해서 between을 걸고 싶습니다.
- column(SomObject::updatedAt::ts) 이런식으로 사용해보려 했는데 안되어서 어떤식으로 접근해야 하는지 궁금합니다.

**Comment by cj848** [comment]
https://github.com/line/kotlin-jdsl#associate
You can refer to .

associate(SomeObject::updatedAt)
where(col(UpdatedAt::ts).equal(value)

You can write it in the form.

-- korean
https://github.com/line/kotlin-jdsl#associate
를 참고하시면 되겠습니다.

associate(SomeObject::updatedAt)
where(col(UpdatedAt::ts).equal(value)

형태로 쓰시면 됩니다.

**Comment by LeeMH** [comment]
@cj848 

감사합니다. :-)
