### ISSUE TITLE
Apply gradle version catalog

### ISSUE THREAD

**Issue by jbl428** [line/kotlin-jdsl#78]
## Suggestion

- Update gradle version to latest
- Apply version catalog (https://docs.gradle.org/current/userguide/platforms.html)
- Migrate `buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/Dependencies.kt` to `libs.version.toml`

## Motivation

- `renovate` does not support `buildSrc` (related issue: https://github.com/renovatebot/renovate/issues/5480)
- `renovate` supports version catalog

If it is applicable, I think I can working on. :)

**Comment by shouwn** [comment]
Hello jbl428, thanks you for the suggestion. I also very sad that renovate does not support buildSrc.

I didn't know about the version catalog until now. 
Looking at the document, it also supports autocomplete and sounds good. But there is no indication that TOML also supports autocomplete in document.

If TOML file supports autocomplete, it would be good to apply TOML as suggested. Even if it don't support autocomplete, it would be good to write versions down only in the `settings.gradle.kts` file.

Thank you for letting me know such a good things.

**Comment by cj848** [comment]
As @shouwn said above, I agree that this is a very good suggestion. If you can try it, please change it, and even if the toml file is not autocompleted in the IDE, it seems to be worthwhile. Because it is expected that the IDE will support it in the future anyway.
