### ISSUE TITLE
How to Automatically add Extra Where Predicates to all Queries?

### ISSUE THREAD

**Issue by MrThreepwood** [line/kotlin-jdsl#786]
We're attempting to switch from the old jakarta builders to jpql. One of the big things we did with Jakarta was provide protected queries, where we could automatically scope queries to the current users authorized access. We could do this because the jakarta builder allowed multiple where statements.

The new JPQL flow is a series of interfaces without ways to modify previous steps. Ideally we'd be able to provide a protected select function that takes a query and appends additional stuff to it, but the only way I can see to do that is to cast the select query to the underlying JpqlSelectQuery which looks like I'm not intended to access.

Is there an easy way to do this with the 3.0 versions?

**Comment by shouwn** [comment]
@MrThreepwood Sorry for the delay in replying.

Could you explain your requirements further with some sample code?

**Comment by shouwn** [comment]
There was no further conversation, so I'm closing the issue. If you have any additional comments, please let me know.
