### ISSUE TITLE
Do you support Stream Query? (Stream 쿼리를 지원하나요?)

### ISSUE THREAD

**Issue by njhyuk** [line/kotlin-jdsl#802]
There was a stream query in the 2.x version, but it doesn't seem to be in 3.x.

2.x 버전대에는 stream 쿼리가 있었으나, 3.x 에는 없는걸로 보여 문의 드립니다.

**Comment by shouwn** [comment]
안녕하세요. `KotlinJdslJpqlExecutor`에 stream 쿼리를 만들지 않았네요. 지원은 가능합니다. 하지만 메소드명을 어떤 것으로 지어야 할지 고민입니다. 

`KotlinJdslJpqlExecutor`의 메소드 시그니처는 Spring의 JpaRepository가 제공하는 것과 최대한 유사하게 제공하는 것을 목표로 삼고 있습니다.

지금 생각 나는 것은 `findStream`인데요. 혹시 stream 관련해서 자주 보셨던 네이밍이 있을까요?

**Comment by shouwn** [comment]
추가로 지금 바로 사용이 필요하시다면 EntityManager를 직접 사용하는 것으로 가능합니다.

`com.linecorp.kotlinjdsl.support.spring.data.jpa.extension.createQuery`가 JPA Query를 반환하기 때문에 이 확장함수들을 사용하시면 됩니다.

**Comment by njhyuk** [comment]
findStream 괜찮은것 같습니다! 안내 감사합니다 👍

**Comment by njhyuk** [comment]
이슈는 직접 닫으시는게 나으실것 같아 열어두었습니다.

**Comment by shouwn** [comment]
넵 이슈는 findStream을 추가한 뒤에 제가 Close하겠습니다.
