### ISSUE TITLE
json 함수를 사용하고싶은데 가능한가요 ?

### ISSUE THREAD

**Issue by kjy991** [line/kotlin-jdsl#805]
```
  kotlinJdslJpqlExecutor
            .findAll {
                selectNew<Response.NoticeData>(
                    path(NoticeEntity::id),
                    path(NoticeEntity::title),
                    path(NoticeEntity::content),
                    path(NoticeEntity::recipients),
                    caseWhen(
                        path(NoticeReadEntity::readYn).isNotNull(),
                    ).then("Y")
                        .`else`("N"),
                    path(NoticeEntity::createdBy),
                    path(NoticeEntity::createdAt),
                    path(NoticeEntity::updatedAt),
                ).from(
                    entity(NoticeEntity::class),
                    leftJoin(entity(NoticeReadEntity::class))
                        .on(path(NoticeReadEntity::notice).path(NoticeEntity::id).equal(path(NoticeEntity::id))),
                ).where(
                    customPredicate(
                        "JSON_CONTAINS({0}, {1})",
                        path(NoticeEntity::recipients),
                        value(recipient),
                    ),
                ).toQuery()
            }.filterNotNull()
```

```
SELECT n.id,
       n.title,
       n.content,
       n.recipients,
       n.created_by,
       n.created_at,
       n.updated_at
FROM `notice` n
         left join notice_read nr on nr.notice_id = n.id
WHERE JSON_CONTAINS(n.recipients, '"b29fadfa-1aee-4ddf-a690-ffe4f04b0e0d"');
```

mysql 사용중이며 3.5.3jdsl 사용중입니다 
[mysql d](driver-class-name: com.mysql.cj.jdbc.Driver)
database-platform: org.hibernate.dialect.MySQLDialect

json 문법을 jdsl에서 사용할수 있나요 ? 아니면 네이티브쿼리로 가야하나요 ?

**Comment by shouwn** [comment]
@kjy991 님 안녕하세요. DB 함수의 경우에는 function을 사용해주셔야 합니다. 
https://kotlin-jdsl.gitbook.io/docs/jpql-with-kotlin-jdsl/expressions#database-function
![image](https://github.com/user-attachments/assets/9665afc4-25b8-4a25-ba4c-9e1ddc92f8ac)

 function을 사용하시면 아래처럼 사용하실 수 있을 거에요.
![image](https://github.com/user-attachments/assets/b9df7d7b-34e7-4b71-a6e8-d975d9ed7533)

**Comment by kjy991** [comment]
답변 주셔서 감사합니다 
추가 문의사항 남겨도될까요 

```
 function(
        Boolean::class,
        "JSON_CONTAINS",
        path(NoticeEntity::recipients),
        "\"$recipient\"",
    ).equal(true)
```
param3 = path(NoticeEntity::recipients)
param3=JpqlEntityProperty(entity=JpqlEntity(type=class com.hakakorea.service.entity.main.NoticeEntity, alias=NoticeEntity), property=var com.hakakorea.service.entity.main.NoticeEntity.recipients: kotlin.collections.List<java.util.UUID>)

```
  function(
        Boolean::class,
        "JSON_CONTAINS",
        "recipients",
        "\"$recipient\"",
    ).equal(true)
```
```
select ne1_0.id,ne1_0.title,ne1_0.content,ne1_0.recipients,case when nre1_0.read_yn is not null then cast('Y' as char) else cast('N' as char) end,ne1_0.created_by,ne1_0.created_at,ne1_0.updated_at from `notice` ne1_0 left join `notice_read` nre1_0 on nre1_0.notice_id=ne1_0.id where json_contains('recipients','"0b27346d-24b1-4568-ad79-585539b149c2"')=true order by ne1_0.created_at desc;
```
'recipients'  홀따움표가 감싸져서 나오고 

```
function(
      Boolean::class,
      "JSON_CONTAINS",
      "${path(NoticeEntity::recipients)}",
      "\"$recipient\"",
  ).equal(true)
```

```
select ne1_0.id,ne1_0.title,ne1_0.content,ne1_0.recipients,case when nre1_0.read_yn is not null then cast('Y' as char) else cast('N' as char) end,ne1_0.created_by,ne1_0.created_at,ne1_0.updated_at from `notice` ne1_0 left join `notice_read` nre1_0 on nre1_0.notice_id=ne1_0.id where json_contains('JpqlEntityProperty(entity=JpqlEntity(type=class com.hakakorea.service.entity.main.NoticeEntity, alias=NoticeEntity), property=var com.hakakorea.service.entity.main.NoticeEntity.recipients: kotlin.collections.List<java.util.UUID>)','"9a7591db-1bc2-4118-9013-eca05aefd13a"')=true order by ne1_0.created_at desc;
```

'JpqlEntityProperty(entity=JpqlEntity(type=class com.hakakorea.service.entity.main.NoticeEntity, alias=NoticeEntity), property=var com.hakakorea.service.entity.main.NoticeEntity.recipients: kotlin.collections.List<java.util.UUID>)' 
이런식으로 매핑이 되어서 나오는데 

```
where json_contains(recipients, '"22eeda6a-a5f9-4296-a914-3bbae6281fcd"') = true
```
jdsl을 사용해서 recipients 가져다 넣는 방법 혹시 있을까요 ?

**Comment by shouwn** [comment]
@kjy991 
function은 2가지 파라미터를 받고 있습니다. 하나는 `vararg args: Any`이고 다른 하나는 `vararg args: Expressionable<*>`
Any의 경우에는 모든 값을 value로 인식하여서 ''을 붙이게 됩니다.

처음에 작성해주신 게 맞는데요. 대신 마지막에 문자열을 value로 감싸서 `vararg args: Expressionable<*>` 함수를 통하도록 해주셔야 합니다.
```
 function(
        Boolean::class,
        "JSON_CONTAINS",
        path(NoticeEntity::recipients),
        value("\"$recipient\""),
    )
```

그리고 https://github.com/line/kotlin-jdsl/issues/726 이슈를 보면 Hibernate 6.5는 function이 정상동작하지 않는 것으로 보입니다. 그래서 처음에 작성해주신 것처럼 customPredicate를 사용한 방법도 한번 시도해봐주세요. customPredicate에서 동작하지 않았던 이유도 위에처럼 마지막 파라미터에 `value()`가 없었기 때문으로 보입니다.

추가로 이는 사용자에게 매우 안 좋은 경험을 줄 수 있다고 생각합니다. 그래서 Kotlin JDSL 내부에서 `vararg args: Any`로 받더라도 Expression일 경우에는 value로 판단하지 않는 로직을 추가하겠습니다.

**Comment by kjy991** [comment]
@shouwn  
친절한 답변 감사합니다

**Comment by shouwn** [comment]
이슈 close 하도록 하겠습니다. 혹시 안 되는 부분이 있으면 다시 오픈해주세요.

**Comment by kjy991** [comment]
1
